<a href="https://colab.research.google.com/github/Eddychege/Neuralnetworks/blob/main/codingneuralnetworksfromscratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Neurons

import numpy as np

inputs = [8.0,6.0,8.5,6.5]
weights = [1.0,2.0,3.0,4.0]
bias = 2.0

inputs_array = np.array(inputs)
weights_array = np.array(weights)

outputs = np.dot(weights_array, inputs_array) + bias
print(outputs)

73.5


In [5]:
# Neural layers

import numpy as np

inputs = [8.0,6.0,8.5,6.5]
weights = [[1.0,2.0,3.0,4.0],
          [5.0,6.0,7.0,8.0],
          [9.0,10.0,11.0,12.0]]
biases = [2.0,3.0,4.0]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

layered_outputs = np.dot(inputs_array, weights_array.T) + biases_array
print(layered_outputs)
layered_outputs = np.dot(weights_array, inputs_array) + biases_array
print(layered_outputs)

[ 73.5 190.5 307.5]
[ 73.5 190.5 307.5]


In [6]:
# Batch layers and data

inputs = [[8.0,6.0,8.5,6.5],
          [9.0,7.0,9.5,7.5],
          [10.0,8.0,10.5,8.5]]
weights = [[1.0,2.0,3.0,4.0],
          [5.0,6.0,7.0,8.0],
          [9.0,10.0,11.0,12.0]]
biases =  [2.0,3.0,4.0]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

batch_layer_outputs = np.dot(inputs_array, weights_array.T) + biases_array
print(batch_layer_outputs)
batch_layer_outputs = np.dot(weights_array, inputs_array.T) + biases_array
print(batch_layer_outputs)

[[ 73.5 190.5 307.5]
 [ 83.5 216.5 349.5]
 [ 93.5 242.5 391.5]]
[[ 73.5  84.5  95.5]
 [189.5 216.5 243.5]
 [305.5 348.5 391.5]]
