<a href="https://colab.research.google.com/github/Eddychege/Neuralnetworks/blob/main/lecture7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.01 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))

  def forward(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases

In [14]:
class ACTIVATION_RELU:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

In [15]:
class ACTIVATION_SOFTMAX:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

In [16]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [17]:
!pip install nnfs

In [19]:
 # Entire foward pass (no loss )
 X,y = spiral_data(samples=100, classes=3)

 dense1 = Layer_Dense(2,3)
 activation1 = ACTIVATION_RELU()
 dense2 = Layer_Dense(3,3)
 activation2 = ACTIVATION_SOFTMAX()

 dense1.forward(X)
 activation1.forward(dense1.output)
 dense2.forward(activation1.output)
 activation2.forward(dense2.output)

 print(activation2.output[:5])


[[0.33333334 0.33333334 0.33333334]
 [0.33333355 0.33333322 0.3333332 ]
 [0.33333382 0.33333313 0.3333331 ]
 [0.3333341  0.33333302 0.33333293]
 [0.33333433 0.3333329  0.33333278]]
